ports:
- port: 8050
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
  - command: >
      pip3 install -r ./requirements.txt &&
      python3 setup.py develop
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - njpwerner.autodocstring@0.4.0:anSzIFYcUMlw2TxiINxxdQ==
