#! /usr/bin/env python3
"""
   to csdfixed
"""

from __future__ import print_function
import sys
import pycsd.csd as csd

sys.path.append('./csd')
print(csd.to_csdfixed(float(sys.argv[1]), int(sys.argv[2])))
