#! /usr/bin/env python
"""
   to csdfixed
"""

from __future__ import print_function
import sys
sys.path.append('./csd')

import pycsd.csd as csd

print (csd.to_csdfixed( float( sys.argv[1]), int( sys.argv[2] )))
